"""
Human-AI Trust Experimentation Engine - FastAPI Backend
=======================================================
REST API for experiment management, condition assignment,
AI recommendations, behavioral logging, and data export.
"""

import json
from datetime import datetime, timezone
import os
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from ai_provider import get_recommendation
from conditions import assign_condition, get_condition, list_all_conditions
from logger import log_event, get_csv_path

# ─── App Setup ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="Human-AI Trust Experimentation Engine",
    description="Modular platform for studying trust calibration in AI-assisted decision systems",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Request / Response Models ───────────────────────────────────────────────


class LogEventRequest(BaseModel):
    participant_id: str
    condition_id: int = Field(ge=1, le=8)
    cue_metadata: dict
    ai_recommendation: str = ""
    scenario_id: Optional[int] = None
    correct_answer: str = ""
    confidence_score: Optional[float] = None
    decision: str = Field(pattern="^(Accept|Override)$")
    latency_ms: float = Field(ge=0)
    timestamp: str


class RecommendationRequest(BaseModel):
    condition_id: int = Field(ge=1, le=8)
    scenario_id: Optional[int] = None


# ─── Routes ──────────────────────────────────────────────────────────────────


@app.get("/")
async def root():
    """Health check endpoint."""
    return {
        "status": "running",
        "service": "Human-AI Trust Experimentation Engine",
        "version": "1.0.0",
    }


@app.post("/api/start")
async def start_experiment():
    """
    Assign a random condition to a new participant.
    Returns participant_id, condition_id, and full condition config (cues).
    """
    assignment = assign_condition()
    return {
        "participant_id": assignment["participant_id"],
        "condition_id": assignment["condition_id"],
        "condition": assignment["condition"],
    }


@app.get("/api/condition/{condition_id}")
async def get_condition_config(condition_id: int):
    """Get the cue configuration for a specific condition (1-8)."""
    try:
        condition = get_condition(condition_id)
        return {"condition_id": condition_id, "condition": condition}
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/api/conditions")
async def list_conditions():
    """List all available conditions and their cue configurations."""
    return {"conditions": list_all_conditions()}


@app.post("/api/recommendation")
async def api_get_recommendation(request: RecommendationRequest):
    """
    Get an AI recommendation for a decision task.

    The recommendation is generated by whichever method the researcher
    has configured in ai_provider.py (hardcoded/proprietary/opensource).
    """
    try:
        condition = get_condition(request.condition_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    try:
        result = get_recommendation(
            condition_id=request.condition_id,
            scenario_id=request.scenario_id,
        )
        return {
            "recommendation": result,
            "condition": condition,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI Provider error: {str(e)}")


@app.post("/api/log")
async def log_decision(event: LogEventRequest):
    """
    Log a participant's decision event to results.csv.
    Captures: participant_id, condition_id, cue_metadata,
    decision (Accept/Override), latency_ms, and timestamp.
    """
    try:
        log_event(event.model_dump())
        return {"status": "logged", "participant_id": event.participant_id}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Logging error: {str(e)}")


@app.get("/admin/export")
async def export_csv():
    """Download the accumulated experiment data as a CSV file."""
    csv_path = get_csv_path()
    if not csv_path.exists():
        raise HTTPException(status_code=404, detail="No data collected yet.")
    return FileResponse(
        path=str(csv_path),
        filename="results.csv",
        media_type="text/csv",
    )


@app.get("/admin/data")
async def get_data_json():
    """Return the accumulated experiment data as JSON (for the admin dashboard)."""
    import csv

    csv_path = get_csv_path()
    if not csv_path.exists():
        return {"data": [], "count": 0}

    rows = []
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    return {"data": rows, "count": len(rows)}


# ─── Entrypoint ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
